---
name: Release Workflow
on:
  release:
    - released
  workflow_dispatch:

jobs:
  release-job:
    runs-on: ubuntu-latest
    steps:
      - name: Debugging
        run: |
          echo Release in Progress
      - name: Debugging Event
        run: |
          echo ${{ github.event.release }}
