---
name: Release Workflow
on:
  release:
    types: [released]

jobs:
  release-job:
    runs-on: ubuntu-latest
    steps:
      - name: Debugging
        run: |
          echo Release in Progress
      - name: Debugging Event
        uses: actions/github-script@v6
        with:
          script: |
            const event = ${{ toJSON(github.event.release) }}
            console.log(JSON.stringify(event, null, 2))
